DROP TABLE IF EXISTS ARTICLES;
CREATE TABLE  ARTICLES (
  `ID_ARTICLE` varchar(45) NOT NULL,
  `DESCRIPTION` varchar(255),
  `PRICE` bigint(20) NOT NULL ,
  `QUANTITY` int NOT NULL,
  `CATEGORY` varchar(255) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  PRIMARY KEY (ID,ID_ARTICLE,CATEGORY)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;
