DROP TABLE IF EXISTS `ASSOCIATION`;
CREATE TABLE `ASSOCIATION` (
  `ID` varchar(3) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) ,
  `R_AMOUNT` bigint(20) NOT NULL,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`,`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO ASSOCIATION (ID, NAME, DESCRIPTION,R_AMOUNT) VALUES ('P10','Parma Dieci','Promotion Etudiants arrivés en 2010',130);




