DROP TABLE IF EXISTS `LOGIN_USERS`;
CREATE TABLE `LOGIN_USERS` (
  `AUTH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` char(15) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUTH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO login_users (USERNAME,PASSWORD) values ('dimitri','dimitri');

ALTER TABLE LOGIN_USERS ADD COLUMN  RMEMBER varchar(25)  AFTER `AUTH_ID`;
