DROP TABLE IF EXISTS `LOGIN_USERS`;
CREATE TABLE `LOGIN_USERS` (
  `AUTH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` char(15) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUTH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LOGIN_USERS ADD COLUMN  RMEMBER varchar(25)  AFTER `AUTH_ID`;
INSERT INTO login_users (RMEMBER,USERNAME,PASSWORD) values ('LION','dimitri','6358b71804dfa8ab069cf05ed1b0ed2a');
