
DROP TABLE IF EXISTS `FUND`;
CREATE TABLE `FUND` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_ASSOCIATION` varchar(3),
  `R_MEMBER` varchar(25)  NOT NULL ,
  `DATE_FUND_START` DATE default current_date,
  `AMOUNT` DECIMAL (19,2) not  null ,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`ID`,`R_MEMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO FUND (ID_ASSOCIATION,R_MEMBER,DATE_FUND_START,AMOUNT) VALUES('P10','KAIZER',current_date,2500);
INSERT INTO FUND (ID_ASSOCIATION,R_MEMBER,DATE_FUND_START,AMOUNT) VALUES('P10','LION',current_date,2500);