DROP TABLE IF EXISTS `GROUPS` ;
CREATE TABLE `GROUPS` (
  `ID` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `ACTIVE`    BOOLEAN,
   `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `GROUPS`   (ID,DESCRIPTION, ACTIVE) values ('P10','Parma 10', true);