CREATE TABLE `MEMBER` (
  `R_ASSOCIATION` varchar(3) NOT NULL DEFAULT 'P10',
  `MNAME` varchar(25) NOT NULL,
  `SURNAME` varchar(50) NOT NULL,
  `SEXE` CHAR(1) ,
  `PHONE` varchar(35) NOT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) DEFAULT 'MEMBRE',
  `ACTIVE`    BOOLEAN,
  `ADMIN`    BOOLEAN,
  STATUS BOOLEAN DEFAULT FALSE,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`R_ASSOCIATION`,`MNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;






