CREATE TABLE `MEMBER` (
  `ID` varchar(3) NOT NULL,
  `MNAME` varchar(25) NOT NULL,
  `SURNAME` varchar(50) NOT NULL,
  `PHONE` varchar(35) NOT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) DEFAULT 'MEMBRE',
  `ACTIVE`    BOOLEAN,
  `ADMIN`    BOOLEAN,
  PRIMARY KEY (`ID`,`MNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE member ADD COLUMN  SEXE CHAR(1)  AFTER `SURNAME`;
ALTER TABLE member ADD COLUMN  STATUS BOOLEAN DEFAULT FALSE;
ALTER TABLE member ADD COLUMN  R_ASSOCIATION varchar(3)  AFTER `ADMIN` DEFAULT 'P10';







