CREATE TABLE `ROLE` (
  `R_ASSOCIATION` varchar(3) NOT NULL,
  `ROLE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `USED` BOOLEAN DEFAULT FALSE,
  `DEFAUT_MBR` BOOLEAN DEFAULT TRUE,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`R_ASSOCIATION`,`ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--ALTER TABLE ROLE ADD COLUMN USED BOOLEAN DEFAULT FALSE;
--UPDATE ROLE SET DEFAUT_MBR=FALSE WHERE ROLE='MBR';

INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','PRS',1,'President',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','SGP',1,'Secretaire General Principale',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','SGA',1,'Secretaire General Adjoint',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','CSP',1,'Censeur principale',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','CSA',1,'Censeur Adjoint',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','TSP',1,'Tresorier Principale',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','TSA',1,'Tresorier Adjoint',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','CCP',1,'Commissaire aux Comptes Principale',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','CCA',1,'Commissaire aux Comptes Adjoint',1);
INSERT INTO ROLE (R_ASSOCIATION, ROLE, DEFAUT_MBR,DESCRIPTION,USED)  VALUES ('P10','MBR',1,'Membre',1);



