CREATE TABLE `ROLE` (
  `R_ASSOCIATION` varchar(3) NOT NULL,
  `ROLE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `USED` BOOLEAN DEFAULT FALSE,
  `DEFAUT_MBR` BOOLEAN DEFAULT TRUE,
  `TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`,`ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--ALTER TABLE ROLE ADD COLUMN USED BOOLEAN DEFAULT FALSE;
--UPDATE ROLE SET DEFAUT_MBR=FALSE WHERE ROLE='MBR';

INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','PRS','President');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','SGP','Secretaire General Principale');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','SGA','Secretaire General Adjoint');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','CSP','Censeur principale');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','CSA','Censeur Adjoint');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','TSP','Tresorier Principale');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','TSA','Tresorier Adjoint');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','CCP','Commissaire aux Comptes Principale');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','CCA','Commissaire aux Comptes Adjoint');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES ('P10','MBR','Membre');



